# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: pwd

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          wget "https://raw.githubusercontent.com/kedarnathdev/rclone/main/rclone.conf" --no-check-certificate -O ".rclone.conf"
          mv .rclone.conf /home/runner
          curl https://rclone.org/install.sh | sudo bash
          rclone config file
          rclone listremotes
          mkdir ~/mydrive
          chmod 775 ~/mydrive/
          rclone --vfs-cache-mode writes mount drive: ~/mydrive -vv --daemon --log-file test.log
          cd ~/mydrive/Tollywood
          wget -c "https://fr15.seedr.cc/ff_get/1089141535/KondaPolam.mkv?st=A2IXwPNCO6srUmiTOXJexg&e=1642269460" --no-check-certificate -O "kondapolam.mkv"
